import { StyleSheet, Dimensions } from "react-native";

const windowWidth = Dimensions.get('window').width;
const isSmallDevice = windowWidth < 375;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#121212",
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: isSmallDevice ? 12 : 20,
    paddingTop: 40,
    borderBottomWidth: 1,
    borderBottomColor: '#2C2C2C',
    backgroundColor: '#1E1E1E',
  },
  headerTitle: {
    fontSize: isSmallDevice ? 18 : 20,
    fontWeight: 'bold',
    color: '#BB86FC',
    flex: 1,
  },
  headerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerButton: {
    padding: isSmallDevice ? 6 : 8,
    marginLeft: isSmallDevice ? 8 : 16,
  },
  contentContainer: {
    flexGrow: 1,
    padding: isSmallDevice ? 12 : 20,
  },
  content: {
    flex: 1,
  },
  workoutHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
    flexWrap: 'wrap',
    gap: 8,
  },
  workoutName: {
    fontSize: isSmallDevice ? 20 : 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    flex: 1,
  },
  editButton: {
    padding: isSmallDevice ? 6 : 8,
  },
  startButton: {
    backgroundColor: "#BB86FC",
    padding: isSmallDevice ? 12 : 16,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 24,
    width: '100%',
    maxWidth: 600,
    alignSelf: 'center',
    minHeight: 48,
    justifyContent: 'center',
  },
  startButtonText: {
    color: "#000",
    fontSize: isSmallDevice ? 16 : 18,
    fontWeight: "bold",
  },
  noWorkoutText: {
    fontSize: isSmallDevice ? 16 : 18,
    color: "#fff",
    textAlign: "center",
    marginBottom: 20,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: isSmallDevice ? 16 : 20,
  },
  emptySubtitle: {
    color: '#666',
    fontSize: isSmallDevice ? 12 : 14,
    textAlign: 'center',
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: "#121212",
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    color: "#BB86FC",
    marginTop: 16,
    fontSize: isSmallDevice ? 14 : 16,
  },
  exerciseContainer: {
    padding: isSmallDevice ? 12 : 20,
    width: '100%',
    maxWidth: 600,
    alignSelf: 'center',
  },
  exerciseName: {
    fontSize: isSmallDevice ? 18 : 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 10,
  },
  setInfo: {
    fontSize: isSmallDevice ? 14 : 16,
    color: '#BB86FC',
    marginBottom: 20,
  },
  inputContainer: {
    marginBottom: 20,
    width: '100%',
  },
  inputGroup: {
    marginBottom: 15,
    width: '100%',
  },
  label: {
    fontSize: isSmallDevice ? 14 : 16,
    color: '#FFFFFF',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#2C2C2C',
    borderRadius: 8,
    padding: isSmallDevice ? 12 : 15,
    color: '#FFFFFF',
    fontSize: isSmallDevice ? 14 : 16,
    borderWidth: 1,
    borderColor: '#BB86FC',
    width: '100%',
    minHeight: 48,
  },
  registerButton: {
    backgroundColor: '#BB86FC',
    padding: isSmallDevice ? 12 : 15,
    borderRadius: 8,
    alignItems: 'center',
    width: '100%',
    minHeight: 48,
    justifyContent: 'center',
  },
  registerButtonText: {
    color: '#000000',
    fontSize: isSmallDevice ? 14 : 16,
    fontWeight: 'bold',
  },
  exerciseCard: {
    backgroundColor: "#1E1E1E",
    borderRadius: 12,
    padding: isSmallDevice ? 12 : 16,
    marginBottom: 16,
    width: '100%',
  },
  exerciseDetails: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: 'wrap',
    gap: 8,
  },
  exerciseInfo: {
    fontSize: isSmallDevice ? 14 : 16,
    color: "#BB86FC",
    flex: 1,
    minWidth: 150,
  },
  fab: {
    position: 'absolute',
    right: isSmallDevice ? 12 : 16,
    bottom: isSmallDevice ? 12 : 16,
    width: isSmallDevice ? 48 : 56,
    height: isSmallDevice ? 48 : 56,
    borderRadius: isSmallDevice ? 24 : 28,
    backgroundColor: '#BB86FC',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
  },
  addWorkoutButton: {
    alignItems: "center",
    padding: isSmallDevice ? 16 : 20,
    width: '100%',
  },
  addWorkoutText: {
    fontSize: isSmallDevice ? 14 : 16,
    color: "#BB86FC",
    marginTop: 10,
  },
});
